version: '3.8'
services:
    database:
        container_name: api_database
        image: 'mariadb:focal'
        ports:
            - '4306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=casasdap_casas
        cap_add:
            - SYS_NICE
        volumes:
            - './docker/mysql/var/lib/mysql:/var/lib/mysql'
            - './docker/mysql/docker-entrypoint-initdb.d:/test'
    php:
        container_name: api_php
        build:
            context: ./docker/php
        ports:
            - '9000:9000'
        volumes:
            - ./:/var/www/symfony_docker
        depends_on:
            - database
    nginx:
        container_name: api_nginx
        build:
            context: ./docker/nginx
        ports:
            - '8080:80'
        volumes:
            - ./:/var/www/symfony_docker
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - database