App\Entity\Admin:
    type: entity
    table: admin
    uniqueConstraints:
        UNIQ_880E0D76E7927C74:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
        roles:
            type: json
            nullable: false
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
