App\Entity\Feedback:
    type: entity
    table: feedback
    indexes:
        cod_casa:
            columns:
                - cod_casa
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        codCasa:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: cod_casa
        valorVoto:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: valor_voto
        comment:
            type: string
            nullable: false
            length: 500
            options:
                fixed: false
        idCliente:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_cliente
        reserva:
            type: integer
            nullable: false
            options:
                unsigned: false
        revisto:
            type: boolean
            nullable: false
        aproved:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
