App\Entity\Mylist:
    type: entity
    table: mylist
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        codCasa:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: cod_casa
        mylistcol:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        sessid:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        cliente:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        data:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
