App\Entity\Periodo:
    type: entity
    table: periodo
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        codCasa:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: cod_casa
        inicio:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        fim:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        precoSemana:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: preco_semana
        precoDia:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: preco_dia
        precoFimsemana:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: preco_fimsemana
        estadiaMinima:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: estadia_minima
        descricao:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        observacoes:
            type: string
            nullable: false
            length: 300
            options:
                fixed: false
    lifecycleCallbacks: {  }
