App\Entity\Proprietariocancelissue:
    type: entity
    table: proprietariocancelissue
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        propid:
            type: integer
            nullable: true
            options:
                unsigned: false
        descricao:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
