App\Entity\ReservaState:
    type: entity
    table: reserva_state
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        state:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
    lifecycleCallbacks: {  }
