App\Entity\TipoPagamento:
    type: entity
    table: tipo_pagamento
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tipoPagamento:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: tipo_pagamento
    lifecycleCallbacks: {  }
