App\Entity\Visita:
    type: entity
    table: visita
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cliente:
            type: integer
            nullable: false
            options:
                unsigned: false
        codCasa:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: cod_casa
        data:
            type: string
            nullable: false
            length: 12
            options:
                fixed: false
        hora:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
    lifecycleCallbacks: {  }
